### ISSUE TITLE
Chinese language in Persian language

### ISSUE THREAD

**Issue by fakhamatia** [KB5201314/UndoForAndroid#1]
Hi
Sorry for bad English
The module work fine in English
But when language of phone is Persian/Farsi it's show Chinese undo redo 
Not necessary to translate Chinese to farsi ,  at least show English to i can find undo redo

**Comment by KB5201314** [comment]
😅sorry for my thoughtless. I will fix it later.
thx.

**Comment by imlk0** [comment]
updated
https://repo.xposed.info/module/top.imlk.undo

thank you!
